### PR TITLE
[Feature: #154190085] Create order model and schema

### PR DESCRIPTION
**Pull request by oreoluwade**
#### What does this PR do?
- It adds the `Order` model and schema.
- It adds an `isAdmin` field to the usermodel so that admin users can be created.

#### Description of Task to be completed?
- Create `Order` model.
- Create `Order` schema.
- Write tests for `Order` schema.

#### How should this be manually tested?
- Checkout into the `ft-create-order-model-and-schema-154190085` branch
- Run recently added migrations with `python3 manage.py migrate`.
- Run the server with `gunicorn config.wsgi`.
- Test the mutations and queries for the `Order` schema.
- Run tests with `coverage run --source=food_basket --omit */snapshots/* manage.py test`

#### Queries and Mutations
The operations to run are as follows:

- `makeOrder`
- `updateOrder`
- `getOneOrder`
- `getUserOrders`
- `cancelOrder`

#### What are the relevant pivotal tracker stories?
- [#154190085](https://www.pivotaltracker.com/story/show/154190085)

#### Extra Details:
- When created, an order is placed on `pending (PEND)` by default. However, running a `cancelOrder` operation sets the status to `cancelled (CANC)`. The screenshots below show two orders in different states.
- once the migrations are run, an admin can be created from the command line with `python3 manage.py createsuperuser`. Still considering if to create a mutation that allows for the creation of an admin.

- The `UpdateOrder` mutation allows for the toggling of the `orderStatus` amongst the three options `PENDING`, `DELIVERED` and `CANCELLED`. Once an order has been delivered however, it can no longer be updated.

#### Screenshots (if appropriate)
screen shot 2018-01-12 at 10 10 01 am
screen shot 2018-01-12 at 10 09 02 am

### CODE REVIEW

**Comment by omorilewa** [comment]
@oreoluwade I am wondering what the second picture in the PR has to do with the PR.

**Comment by oreoluwade** [comment]
@omorilewa It was an error. Now rectified.

**Comment by omorilewa** [comment]
@oreoluwade Also I think it should be possible to cancel an order. However, only the admin should be permitted to do so. Could you kindly add a mutation thst enables an admin to cancel an order.

**Comment by omorilewa** [comment]
@oreoluwade What I meant to say. I think it is only a superadmin that should be able to update orders. Is it possible to confirm the userId prior to running that mutation.

**Comment by omorilewa** [comment]
@oreoluwade Responding to your questions:

1. An admin is a superuser i.e a user whose  `isAdmin` field is set to true.
2. An admin should update an order, not the store owner. While the order is being processed, if the store owner cannot proceed, the admin would be contacted and he/she would modify the order.
3.The former is the case.

**Comment by oreoluwade** [comment]
@omorilewa Sure, it's possible to check the `adminStatus` of a user before performing a `cancelOrder` mutation. I will work on that.

**Comment by oreoluwade** [comment]
And yes, I agree. A regular user should not have the power to indiscriminately cancel orders, else, there'd be chaos. Thanks for bringing those details to my attention @omorilewa. Will make the necessary changes.

**Comment by fisayomi** [comment]
@omorilewa @oreoluwade ,  I think update can be possible at the backend but we will not enable users to update from the frontend. They will be another interface for superusers to effect any update from the frontend

**Comment by oreoluwade** [comment]
I only made two fields available for update, the `address` as well as the `phoneNumber`. My thinking was that within a time frame, perhaps it'd be nice to have the option to change those details in the case that you got it wrong or so.

But now that you mention, I am thinking of how changing the address might present problems to the admin. 

Extra thoughts @omorilewa @fisayomi?

**Comment by fisayomi** [comment]
@oreoluwade I think you can make all fields available for update from the backend. we will only limit the fields available from the frontend depending on the user type

**Comment by oreoluwade** [comment]
Okay. Sounds good.

**Comment by oreoluwade** [comment]
@omorilewa, Do you think that the suggestion given above by @fisayomi should apply to the `cancelOrder` mutation as well such that there's no access to the mutation unless the user is a `superAdmin`?

**Comment by omorilewa** [comment]
Is there a `cancelOrder` mutation, or you are referring to the `updateOrder`.I agree all fields should be available for update by the superadmin. I also think the use should not be able to perform any update whatsoever. If the user needs to, he/she should contact an admin.

**Comment by oreoluwade** [comment]
@omorilewa 😆  Please, kindly check the `order` schema in the files changed, there is a cancelOrder mutation. I have not edited it yet base don your advice, but it exists.

**Comment by omorilewa** [comment]
@oreoluwade If it exists, would you be gracious enough to include it in the PR description. I assumed one could get up to speed by reading through the description without necessarily digging deep.

**Comment by oreoluwade** [comment]
@omorilewa Perhaps you did not check the PR description well enough. 🤣

**Comment by omorilewa** [comment]
@oreoluwade It got updated later on. I was looking at the initial PR you made.

**Comment by oreoluwade** [comment]
@omorilewa I just realized that our user has no `isAdmin` field. Do you know if this has always been the case or is a recent development?

**Comment by omorilewa** [comment]
@oreoluwade I must commend you on this. Well done!

**Pull request merged**
