### PR TITLE
[Feature: #164399365] Create category model and schema

### PR DESCRIPTION
**Pull request by fisayomi**
#### What does this PR do?
- Creates the Category model
- Creates the Category Schema with queries and mutations

#### Description of Task to be completed?
An authorized user should be able to create product categories. 

#### How should this be manually tested?
 - Run the app
 - run the migration
 - Test the category queries and mutations

#### Any background context you want to provide?
 - Note that creating a sub-category was taken into consideration, thus the `parent_id` field in Category table

#### What are the relevant pivotal tracker stories?
[#164399365](https://www.pivotaltracker.com/story/show/164399365)

### CODE REVIEW

**Comment by oreoluwade** [comment]
I have seen the context comment comment about the sub-category not being taken into consideration, but I am afraid I still do not understand what the `parent_id` is for. Could you shed some more light?

**Comment by fisayomi** [comment]
> I have seen the context comment comment about the sub-category not being taken into consideration, but I am afraid I still do not understand what the `parent_id` is for. Could you shed some more light?

Hey @oreoluwade , there are instances where we would need to create sub-categories, in that case, the `parent_id` field will be the id of the parent category. If it is the root category, `parent_id` will be null. Hope this helps.

**Comment by oreoluwade** [comment]
> > I have seen the context comment comment about the sub-category not being taken into consideration, but I am afraid I still do not understand what the `parent_id` is for. Could you shed some more light?
> 
> Hey @oreoluwade , there are instances where we would need to create sub-categories, in that case, the `parent_id` field will be the id of the parent category. If it is the root category, `parent_id` will be null. Hope this helps.

Yes, it helps. Thanks.

**Comment by omorilewa** [comment]
@fisayomi Just to be clear, would the subcategories also be in the Categories table?

**Comment by fisayomi** [comment]
> @fisayomi Just to be clear, would the subcategories also be in the Categories table?

Yes Please.

**Pull request merged**
